package com.jeffstrunk.TimeTrackerWServlets;

public enum ActivityType {
	UNDEFINED,
	SLEEPING,
	MORNING_NIGHT_PREP_BATHING,
	COOKING_EATING,
	IN_TRANSIT,
	WORKING,
	EXERCISING,
	SOCIALIZING,
	CLEANING_LAUNDRY,
	LEISURE_ENTERTAINMENT,
	YOUTUBE,
	ANIME,
	PHONE_BROWSING

}
